### ISSUE TITLE
Title of README does not render correctly on crates.io

### ISSUE THREAD

**Issue by alexreg** [bh1xuw/rust-rocks#4]
See <https://crates.io/crates/rocks>. Perhaps the Markdown supported by crates.io is a bit different? It seems other projects have found a solution that works for both, however.

**Comment by bh1xuw** [comment]
Yes, the badge icon links are broken. I'll fix it.

**Comment by bh1xuw** [comment]
Fixed and published as 0.1.1.
Looks better now, :)

**Comment by alexreg** [comment]
Great. Might want to add a crates.io badge while you're at it... small things, I know. ;-)
